<a href="https://colab.research.google.com/github/MSaadT313/NLP-SummerCamp-CRAAT/blob/main/Copy_of_1_NLP_Pipeline_with_Truncation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP Pipeline: Raw Text → Padded Sequences
Includes cleaning, normalization, tokenization, OOV handling, vocabulary, sequences, padding, and truncation examples.

In [ ]:
import re, pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
corpus=[
'I love Natural Language Processing!',
'Deep Learning models perform well.',
'Machine learning is transforming healthcare.',
'Artificial Intelligence is changing the world.',
'Neural networks learn useful representations.',
'Transformers outperform RNNs on many tasks.',
'LSTM networks are good for sequence learning.',
'NLP enables computers to understand language.',
'Text preprocessing improves model performance.',
'Data cleaning is an essential first step.'
]

In [ ]:
pip install urduhack

Collecting urduhack
  Downloading urduhack-1.1.1-py3-none-any.whl.metadata (7.2 kB)
Collecting tf2crf (from urduhack)
  Downloading tf2crf-0.1.33-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting tensorflow-datasets~=3.1 (from urduhack)
  Downloading tensorflow_datasets-3.2.1-py3-none-any.whl.metadata (4.8 kB)
Collecting Click~=7.1 (from urduhack)
  Downloading click-7.1.2-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from urduhack) (2025.11.3)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (1.4.0)
Requirement already satisfied: attrs>=18.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (26.1.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (0.3.8)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (1.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (2.0.2)
Requirement already satisfied: promise in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (2.3)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (5.29.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (2.32.4)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (1.17.0)
Requirement already satisfied: tensorflow-metadata in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (1.21.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (3.3.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (4.67.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from tensorflow-datasets~=3.1->urduhack) (2.2.2)
Requirement already satisfied: tensorflow>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from tf2crf->urduhack) (2.20.0)
INFO: pip is looking at multiple versions of tf2crf to determine which version is compatible with other requirements. This could take a while.
Collecting tf2crf (from urduhack)
  Downloading tf2crf-0.1.32-py2.py3-none-any.whl.metadata (1.9 kB)
  Downloading tf2crf-0.1.31-py2.py3-none-any.whl.metadata (1.9 kB)
  Downloading tf2crf-0.1.30-py2.py3-none-any.whl.metadata (1.9 kB)
  Downloading tf2crf-0.1.29-py2.py3-none-any.whl.metadata (3.6 kB)
  Downloading tf2crf-0.1.28-py2.py3-none-any.whl.metadata (3.6 kB)
  Downloading tf2crf-0.1.27-py2.py3-none-any.whl.metadata (2.9 kB)
  Downloading tf2crf-0.1.26-py2.py3-none-any.whl.metadata (2.9 kB)
INFO: pip is still looking at multiple versions of tf2crf to determine which version is compatible with other requirements. This could take a while.
  Downloading tf2crf-0.1.25-py2.py3-none-any.whl.metadata (2.9 kB)
  Downloading tf2crf-0.1.24-py2.py3-none-any.whl.metadata (2.7 kB)
  Downloading tf2crf-0.1.23-py2.py3-none-any.whl.metadata (2.7 kB)
  Downloading tf2crf-0.1.22-py2.py3-none-any.whl.metadata (2.7 kB)
  Downloading tf2crf-0.1.21-py2.py3-none-any.whl.metadata (2.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading tf2crf-0.1.20-py2.py3-none-any.whl.metadata (2.4 kB)
  Downloading tf2crf-0.1.19-py2.py3-none-any.whl.metadata (2.4 kB)
  Downloading tf2crf-0.1.18-py2.py3-none-any.whl.metadata (2.4 kB)
  Downloading tf2crf-0.1.17-py2.py3-none-any.whl.metadata (2.4 kB)
  Downloading tf2crf-0.1.16-py2.py3-none-any.whl.metadata (2.4 kB)
  Downloading tf2crf-0.1.15-py2.py3-none-any.whl.metadata (2.3 kB)
  Downloading tf2crf-0.1.14-py2.py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.13-py2.py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.12-py2.py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.8-py2.py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.6-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.5-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.4-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.3-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading tf2crf-0.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting urduhack
  Downloading urduhack-1.1.0-py3-none-any.whl.metadata (7.2 kB)
  Downloading urduhack-1.0.3-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->tensorflow-datasets~=3.1->urduhack) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->tensorflow-datasets~=3.1->urduhack) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->tensorflow-datasets~=3.1->urduhack) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->tensorflow-datasets~=3.1->urduhack) (2026.6.17)
Requirement already satisfied: googleapis-common-protos<2,>=1.56.4 in /usr/local/lib/python3.12/dist-packages (from tensorflow-metadata->tensorflow-datasets~=3.1->urduhack) (1.75.0)
Downloading urduhack-1.0.3-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.0/98.0 kB 1.9 MB/s eta 0:00:00
Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 5.3 MB/s eta 0:00:00
Downloading tensorflow_datasets-3.2.1-py3-none-any.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 24.9 MB/s eta 0:00:00
Installing collected packages: Click, tensorflow-datasets, urduhack
  Attempting uninstall: Click
    Found existing installation: click 8.4.2
    Uninstalling click-8.4.2:
      Successfully uninstalled click-8.4.2
  Attempting uninstall: tensorflow-datasets
    Found existing installation: tensorflow-datasets 4.9.10
    Uninstalling tensorflow-datasets-4.9.10:
      Successfully uninstalled tensorflow-datasets-4.9.10
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires click<9,>=8.1.8, but you have click 7.1.2 which is incompatible.
huggingface-hub 1.23.0 requires click<9.0.0,>=8.4.2, but you have click 7.1.2 which is incompatible.
wandb 0.28.0 requires click>=8.2.0, but you have click 7.1.2 which is incompatible.
flask 3.1.3 requires click>=8.1.3, but you have click 7.1.2 which is incompatible.
dask 2026.7.0 requires click>=8.1, but you have click 7.1.2 which is incompatible.
Successfully installed Click-7.1.2 tensorflow-datasets-3.2.1 urduhack-1.0.3

## 1. Raw Text
Displays the original corpus.

In [ ]:
corpus = [
    'The old bicycle was leaning against a broken fence.',
    'She forgot her umbrella even though the forecast predicted heavy rain.',
    'A tiny kitten slept peacefully inside the empty cardboard box.',
    'My grandfather still writes letters using a fountain pen.',
    'The chef accidentally added too much salt to the soup.',
    'Students were discussing their vacation plans during lunch break.',
    'An astronaut dreams of walking on Mars one day.',
    'The museum displayed ancient coins from different civilizations.',
    'Fresh coffee filled the kitchen with a wonderful aroma.',
    'Several birds gathered near the lake before sunrise.',
    'He misplaced his wallet somewhere between the bookstore and the station.',
    'The curious child asked hundreds of questions about the stars.',
    'Our neighbors planted colorful flowers along the sidewalk.',
    'The train arrived twenty minutes later than expected.',
    'A strong wind knocked down several tree branches overnight.',
    'She enjoys solving crossword puzzles every Sunday morning.',
    'The carpenter built a wooden table without using any nails.',
    'Everyone applauded when the young pianist finished her performance.',
    'A mysterious package appeared at the front door this morning.',
    'The local bakery sells delicious bread and homemade cookies.',
    'His smartphone battery died in the middle of an important call.',
    'Bright balloons decorated the hall for the birthday celebration.',
    'The fisherman waited patiently for hours without catching a single fish.',
    'After the meeting, everyone shared ideas over a cup of tea.',
    'Despite the unexpected power outage, the event continued successfully.'
]

In [ ]:
corpus = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<title>Sample HTML Document</title>',
'</head>',
'<body>',
'<h1>Welcome to My Website</h1>',
'<p>This is the first paragraph about Natural Language Processing.</p>',
'<p>Machine Learning helps computers learn from data.</p>',
'<a href="https://www.example.com">Visit Example</a>',
'<img src="image.jpg" alt="Sample Image">',
'<h2>About Us</h2>',
'<p>We build AI applications for education and healthcare.</p>',
'<ul>',
'<li>Python</li>',
'<li>Java</li>',
'<li>C++</li>',
'</ul>',
'<h2>Services</h2>',
'<ol>',
'<li>Web Development</li>',
'<li>Data Science</li>',
'<li>Artificial Intelligence</li>',
'</ol>',
'<p>Email us at contact@example.com</p>',
'<p>Call us at +1-123-456-7890</p>',
'<hr>',
'<h3>Latest News</h3>',
'<p>Today is a sunny day with pleasant weather.</p>',
'<p>Our company launched a new AI chatbot.</p>',
'<a href="https://openai.com">OpenAI</a>',
'<p>Special Offer: 50% Discount!</p>',
'<table border="1">',
'<tr>',
'<th>Name</th>',
'<th>Age</th>',
'<th>City</th>',
'</tr>',
'<tr>',
'<td>Ali</td>',
'<td>25</td>',
'<td>Karachi</td>',
'</tr>',
'<tr>',
'<td>John</td>',
'<td>30</td>',
'<td>London</td>',
'</tr>',
'</table>',
'<h2>Registration Form</h2>',
'<form>',
'<label>Name:</label>',
'<input type="text" placeholder="Enter Name">',
'<label>Email:</label>',
'<input type="email" placeholder="Enter Email">',
'<label>Password:</label>',
'<input type="password">',
'<button>Register</button>',
'</form>',
'<h2>Testimonials</h2>',
'<p>Excellent service and fast support.</p>',
'<p>Highly recommended for beginners.</p>',
'<div class="content">',
'<p>Artificial Intelligence is transforming industries.</p>',
'</div>',
'<section>',
'<h3>Blog Post</h3>',
'<p>Deep Learning models require large datasets.</p>',
'<p>Neural Networks consist of multiple layers.</p>',
'</section>',
'<footer>',
'<p>Copyright © 2026 My Company</p>',
'<p>All Rights Reserved.</p>',
'</footer>',
'<!-- This is a sample HTML comment -->',
'<p>Contact support 24/7 for assistance.</p>',
'<p>Price: $499 only.</p>',
'<p>Order ID: 987654321</p>',
'<p>Happy Coding! 😊 🚀</p>',
'<p>#ArtificialIntelligence #Python</p>',
'<p>Visit www.samplewebsite.com today.</p>',
'<p>HTML is the structure of a web page.</p>',
'<p>CSS styles the webpage beautifully.</p>',
'<p>JavaScript makes web pages interactive.</p>',
'<p>Data preprocessing is important for NLP.</p>',
'<p>Tokenization splits text into words.</p>',
'<p>Stopword removal improves efficiency.</p>',
'<p>Stemming reduces words to root forms.</p>',
'<p>Lemmatization finds meaningful base words.</p>',
'<p>Bag of Words is a simple NLP technique.</p>',
'<p>TF-IDF measures word importance.</p>',
'<p>Transformers power modern language models.</p>',
'<p>Thank you for visiting our website.</p>',
'</body>',
'</html>'
]

In [ ]:
corpus = [
    'آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے۔',
    'علی ہر صبح پارک میں دوڑنے جاتا ہے۔',
    'مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے۔',
    'بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں۔',
    'ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی۔',
    'کتاب پڑھنے سے علم میں اضافہ ہوتا ہے۔',
    'بازار میں آج بہت زیادہ رش تھا۔',
    'بارش کی وجہ سے سڑکیں پانی سے بھر گئیں۔',
    'استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ہدایت دی۔',
    'میری بہن بہت اچھا کھانا بناتی ہے۔',
    'مسافر وقت پر اسٹیشن پہنچ گئے۔',
    'درختوں پر پرندے صبح سویرے چہچہا رہے تھے۔',
    'ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے۔'
]

## 2. Cleaning
HTML, URLs, emojis, hashtags, digits, punctuation removed; lowercase and whitespace normalized.

## 3. Flow
Raw → Cleaned

In [ ]:
def clean(t):
 t=re.sub(r'<[^>]+>',' ',t)
 t=re.sub(r'https?://\S+|www\.\S+',' ',t)
 t=re.sub(r'[\U0001F300-\U0001FAFF\U00002700-\U000027BF]',' ',t)
 t=re.sub(r'#\w+',' ',t)
 t=re.sub(r'\d+',' ',t)
 t=re.sub(r'[^\w\s]',' ',t)
 return re.sub(r'\s+',' ',t).strip().lower()
cleaned=[clean(x) for x in corpus]
pd.DataFrame({'Raw':corpus,'Cleaned':cleaned})

,Raw,Cleaned
0,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے۔,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے
1,علی ہر صبح پارک میں دوڑنے جاتا ہے۔,علی ہر صبح پارک میں دوڑنے جاتا ہے
2,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے۔,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے
3,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں۔,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں
4,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات...,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی
5,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے۔,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے
6,بازار میں آج بہت زیادہ رش تھا۔,بازار میں آج بہت زیادہ رش تھا
7,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں۔,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں
8,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...
9,میری بہن بہت اچھا کھانا بناتی ہے۔,میری بہن بہت اچھا کھانا بناتی ہے
10,مسافر وقت پر اسٹیشن پہنچ گئے۔,مسافر وقت پر اسٹیشن پہنچ گئے
11,درختوں پر پرندے صبح سویرے چہچہا رہے تھے۔,درختوں پر پرندے صبح سویرے چہچہا رہے تھے
12,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے۔,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے

## Optional preprocessing
Stopword removal, stemming, and lemmatization are shown as optional because modern deep learning often skips them.

In [ ]:
import nltk
nltk.download('stopwords',quiet=True); nltk.download('wordnet',quiet=True)
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
sw=set(stopwords.words('english'))
ps=PorterStemmer(); lm=WordNetLemmatizer()
demo=pd.DataFrame({
'Cleaned':cleaned,
'No Stopwords':[' '.join(w for w in s.split() if w not in sw) for s in cleaned],
'Stemmed':[' '.join(ps.stem(w) for w in s.split()) for s in cleaned],
'Lemmatized':[' '.join(lm.lemmatize(w) for w in s.split()) for s in cleaned]})
demo

,Cleaned,No Stopwords,Stemmed,Lemmatized
0,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے
1,علی ہر صبح پارک میں دوڑنے جاتا ہے,علی ہر صبح پارک میں دوڑنے جاتا ہے,علی ہر صبح پارک میں دوڑنے جاتا ہے,علی ہر صبح پارک میں دوڑنے جاتا ہے
2,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے
3,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں
4,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی
5,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے
6,بازار میں آج بہت زیادہ رش تھا,بازار میں آج بہت زیادہ رش تھا,بازار میں آج بہت زیادہ رش تھا,بازار میں آج بہت زیادہ رش تھا
7,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں
8,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...
9,میری بہن بہت اچھا کھانا بناتی ہے,میری بہن بہت اچھا کھانا بناتی ہے,میری بہن بہت اچھا کھانا بناتی ہے,میری بہن بہت اچھا کھانا بناتی ہے
10,مسافر وقت پر اسٹیشن پہنچ گئے,مسافر وقت پر اسٹیشن پہنچ گئے,مسافر وقت پر اسٹیشن پہنچ گئے,مسافر وقت پر اسٹیشن پہنچ گئے
11,درختوں پر پرندے صبح سویرے چہچہا رہے تھے,درختوں پر پرندے صبح سویرے چہچہا رہے تھے,درختوں پر پرندے صبح سویرے چہچہا رہے تھے,درختوں پر پرندے صبح سویرے چہچہا رہے تھے
12,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے

## Tokenization and Vocabulary
Flow: Cleaned Text → Tokens → Integer IDs

In [ ]:
tok=Tokenizer(oov_token='<OOV>')
tok.fit_on_texts(cleaned)
seq=tok.texts_to_sequences(cleaned)
pd.DataFrame(tok.word_index.items(),columns=['Word','ID']).head(20)

       Word  ID
0     <OOV>   1
1        ہے   2
2       میں   3
3        سے   4
4       بہت   5
5        کے   6
6        نے   7
7        کی   8
8        پر   9
9        آج  10
10      صبح  11
11    کھانا  12
12      رہے  13
13       ہم  14
14      وقت  15
15     موسم  16
16  خوشگوار  17
17      اور  18
18     ہلکی  19
19      ہوا  20

## Integer Sequences

In [ ]:
pd.DataFrame({'Sentence':cleaned,'Sequence':seq})

,Sentence,Sequence
0,آج موسم بہت خوشگوار ہے اور ہلکی ہوا چل رہی ہے,"[10, 16, 5, 17, 2, 18, 19, 20, 21, 22, 2]"
1,علی ہر صبح پارک میں دوڑنے جاتا ہے,"[23, 24, 11, 25, 3, 26, 27, 2]"
2,مجھے چائے کے ساتھ بسکٹ کھانا پسند ہے,"[28, 29, 6, 30, 31, 12, 32, 2]"
3,بچے اسکول میں نئی کہانیاں سیکھ رہے ہیں,"[33, 34, 3, 35, 36, 37, 13, 38]"
4,ہم نے ہفتے کے آخر میں اپنے دادا دادی سے ملاقات کی,"[14, 7, 39, 6, 40, 3, 41, 42, 43, 4, 44, 8]"
5,کتاب پڑھنے سے علم میں اضافہ ہوتا ہے,"[45, 46, 4, 47, 3, 48, 49, 2]"
6,بازار میں آج بہت زیادہ رش تھا,"[50, 3, 10, 5, 51, 52, 53]"
7,بارش کی وجہ سے سڑکیں پانی سے بھر گئیں,"[54, 8, 55, 4, 56, 57, 4, 58, 59]"
8,استاد نے تمام طلبہ کو وقت پر کام مکمل کرنے کی ...,"[60, 7, 61, 62, 63, 15, 9, 64, 65, 66, 8, 67, 68]"
9,میری بہن بہت اچھا کھانا بناتی ہے,"[69, 70, 5, 71, 12, 72, 2]"
10,مسافر وقت پر اسٹیشن پہنچ گئے,"[73, 15, 9, 74, 75, 76]"
11,درختوں پر پرندے صبح سویرے چہچہا رہے تھے,"[77, 9, 78, 11, 79, 80, 13, 81]"
12,ہم سب نے مل کر یتیم خانے کے لیے عطیات جمع کیے,"[14, 82, 7, 83, 84, 85, 86, 6, 87, 88, 89, 90]"

## Padding Examples
Compare pre-padding and post-padding.

In [ ]:
maxlen=max(map(len,seq))
post=pad_sequences(seq,maxlen=maxlen,padding='post')
pre=pad_sequences(seq,maxlen=maxlen,padding='pre')
print('Max length:',maxlen)
pd.DataFrame({'Original':seq,'Post Padding':post.tolist(),'Pre Padding':pre.tolist()})

Max length: 13

,Original,Post Padding,Pre Padding
0,"[10, 16, 5, 17, 2, 18, 19, 20, 21, 22, 2]","[10, 16, 5, 17, 2, 18, 19, 20, 21, 22, 2, 0, 0]","[0, 0, 10, 16, 5, 17, 2, 18, 19, 20, 21, 22, 2]"
1,"[23, 24, 11, 25, 3, 26, 27, 2]","[23, 24, 11, 25, 3, 26, 27, 2, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 23, 24, 11, 25, 3, 26, 27, 2]"
2,"[28, 29, 6, 30, 31, 12, 32, 2]","[28, 29, 6, 30, 31, 12, 32, 2, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 28, 29, 6, 30, 31, 12, 32, 2]"
3,"[33, 34, 3, 35, 36, 37, 13, 38]","[33, 34, 3, 35, 36, 37, 13, 38, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 33, 34, 3, 35, 36, 37, 13, 38]"
4,"[14, 7, 39, 6, 40, 3, 41, 42, 43, 4, 44, 8]","[14, 7, 39, 6, 40, 3, 41, 42, 43, 4, 44, 8, 0]","[0, 14, 7, 39, 6, 40, 3, 41, 42, 43, 4, 44, 8]"
5,"[45, 46, 4, 47, 3, 48, 49, 2]","[45, 46, 4, 47, 3, 48, 49, 2, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 45, 46, 4, 47, 3, 48, 49, 2]"
6,"[50, 3, 10, 5, 51, 52, 53]","[50, 3, 10, 5, 51, 52, 53, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 50, 3, 10, 5, 51, 52, 53]"
7,"[54, 8, 55, 4, 56, 57, 4, 58, 59]","[54, 8, 55, 4, 56, 57, 4, 58, 59, 0, 0, 0, 0]","[0, 0, 0, 0, 54, 8, 55, 4, 56, 57, 4, 58, 59]"
8,"[60, 7, 61, 62, 63, 15, 9, 64, 65, 66, 8, 67, 68]","[60, 7, 61, 62, 63, 15, 9, 64, 65, 66, 8, 67, 68]","[60, 7, 61, 62, 63, 15, 9, 64, 65, 66, 8, 67, 68]"
9,"[69, 70, 5, 71, 12, 72, 2]","[69, 70, 5, 71, 12, 72, 2, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 69, 70, 5, 71, 12, 72, 2]"
10,"[73, 15, 9, 74, 75, 76]","[73, 15, 9, 74, 75, 76, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 73, 15, 9, 74, 75, 76]"
11,"[77, 9, 78, 11, 79, 80, 13, 81]","[77, 9, 78, 11, 79, 80, 13, 81, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 77, 9, 78, 11, 79, 80, 13, 81]"
12,"[14, 82, 7, 83, 84, 85, 86, 6, 87, 88, 89, 90]","[14, 82, 7, 83, 84, 85, 86, 6, 87, 88, 89, 90, 0]","[0, 14, 82, 7, 83, 84, 85, 86, 6, 87, 88, 89, 90]"

## Truncation Examples
Illustrates truncating long sequences from the beginning or end.

In [ ]:
long_seq=[list(range(1,16))]
post_trunc=pad_sequences(long_seq,maxlen=8,truncating='post')
pre_trunc=pad_sequences(long_seq,maxlen=8,truncating='pre')
print('Original:',long_seq[0])
print('Post truncation:',post_trunc[0].tolist())
print('Pre truncation :',pre_trunc[0].tolist())

Original: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Post truncation: [1, 2, 3, 4, 5, 6, 7, 8]
Pre truncation : [8, 9, 10, 11, 12, 13, 14, 15]

## Final Input Matrix
The padded matrix is the input to an Embedding layer followed by an LSTM.

In [ ]:
X=post
print(X.shape)
X

(13, 13)

array([[10, 16,  5, 17,  2, 18, 19, 20, 21, 22,  2,  0,  0],
       [23, 24, 11, 25,  3, 26, 27,  2,  0,  0,  0,  0,  0],
       [28, 29,  6, 30, 31, 12, 32,  2,  0,  0,  0,  0,  0],
       [33, 34,  3, 35, 36, 37, 13, 38,  0,  0,  0,  0,  0],
       [14,  7, 39,  6, 40,  3, 41, 42, 43,  4, 44,  8,  0],
       [45, 46,  4, 47,  3, 48, 49,  2,  0,  0,  0,  0,  0],
       [50,  3, 10,  5, 51, 52, 53,  0,  0,  0,  0,  0,  0],
       [54,  8, 55,  4, 56, 57,  4, 58, 59,  0,  0,  0,  0],
       [60,  7, 61, 62, 63, 15,  9, 64, 65, 66,  8, 67, 68],
       [69, 70,  5, 71, 12, 72,  2,  0,  0,  0,  0,  0,  0],
       [73, 15,  9, 74, 75, 76,  0,  0,  0,  0,  0,  0,  0],
       [77,  9, 78, 11, 79, 80, 13, 81,  0,  0,  0,  0,  0],
       [14, 82,  7, 83, 84, 85, 86,  6, 87, 88, 89, 90,  0]], dtype=int32)